language: node_js
node_js: 
  - "8"
dist: trusty
env:
  - NODE_ENV=ci PORT=3000
services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - cd client
  - npm install
  - npm run build
  - cd ..
script:
  - nohup npm start &
  - sleep 3
branches:
  only:
    - new-changes



