language: node_js
node_js: 
  - "8"
dist: trusty
env:
  - NODE_ENV=ci PORT=3000
services:
  - mongodb
  - redis-server
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - cat /home/travis/.npm/_logs/2019-09-12T02_45_24_222Z-debug.log
script:
  - nohup npm start &
  - sleep 3
branches:
  only:
    - new-changes



